### ISSUE TITLE
Utilize Vercel Image optimizations

### ISSUE THREAD

**Issue by MichaelTamaki** [CodeWithAloha/CWAWebsite#16]
We should not be using `img` HTML tags like so: https://github.com/CodeWithAloha/CWAWebsite/blob/7b5d692840c932f290992ea22cfe9b81d60081fc/src/components/Logo.js#L11

Vercel comes with image optimization built-in.

> [Image Optimization](https://vercel.com/docs/image-optimization) helps you achieve faster page loads by reducing the size of images and using modern image formats.
> 
> https://vercel.com/docs/frameworks/nextjs#image-optimization

We can replace instances of `img` with `Image` from Vercel. 

Edit 9/18/23: You can find these issues by running `npm run lint`!

**Comment by kobebuckley** [comment]
Thank you, { npm run lint } was a huge help in finding the issues!
