### ISSUE TITLE
add a PR template for our repo

### ISSUE THREAD

**Issue by Alexandra-Haynes** [CodeWithAloha/CWAWebsite#27]
**Why:** 
Adding a Pull Request (PR) template to this repository can be a great way to ensure all contributors provide consistent and necessary information when submitting PRs, making it easier and faster to review them.
**How:** 
1. **Create a PT template file:** in the root directory, create a file called **_PULL_REQUEST_TEMPLATE.md_** 
2. **Add content** - my idea: 
---
## Summary:

Please provide a brief description of the changes made in this PR for the "Code with Aloha Website".

## Changes:

- [ ] Updated Section (please specify which section)
- [ ] Added new feature (please describe)
- [ ] Fixed a bug (please describe)
- [ ] Updated documentation

## Related Issue:

Please link to any related issue or provide context for the changes.

## Screenshots:

If your changes affect the UI or layout, please attach before-and-after screenshots.

## How I Tested:

Please describe how you tested the changes (e.g., locally, on the live site, etc.).

## Notes:

Any additional information or context about the changes.

Thank you for contributing to the Code with Aloha Website! We appreciate your effort and dedication to improving the community through technology.

---
3. **Commit and push the changes**
4. **Testing the template** - next time someone opens a PR for this repo, they will see the template in the PR description - yey! 🎈

**Comment by sarafurd** [comment]
Please assign this to me

**Comment by sarafurd** [comment]
**Summary:**
Please provide a brief description of the changes made in this PR for the "Code with Aloha Website".

**Changes:**
- **Updated Section:** (please specify which section)
- **Added new feature:** (please describe)
- **Fixed a bug:** (please describe)
- **Updated documentation**

**Related Issue:**
Please link to any related issue or provide context for the changes.

**Screenshots:**
If your changes affect the UI or layout, please attach before-and-after screenshots.

**How I Tested:**
Please describe how you tested the changes (e.g., locally, on the live site, etc.).

**Notes:**
Any additional information or context about the changes.

Thank you for contributing to the Code with Aloha Website! We appreciate your effort and dedication to improving the community through technology.

Commit and push the changes
guidelines for commit

**Comment by sarafurd** [comment]
# Summary:
Please provide a brief description of the changes made in this PR for the "Code with Aloha Website".

# Changes:
- **Updated Section:** (please specify which section)
- **Added new feature:** (please describe)
- **Fixed a bug:** (please describe)
- **Updated documentation**

# Related Issue:
Please link to any related issue or provide context for the changes.

# Screenshots:
If your changes affect the UI or layout, please attach before-and-after screenshots.

# How I Tested:
Please describe how you tested the changes (e.g., locally, on the live site, etc.).

# Notes:
Any additional information or context about the changes.

Thank you for contributing to the Code with Aloha Website! We appreciate your effort and dedication to improving the community through technology.

Commit and push the changes
guidelines for commit?
