### ISSUE TITLE
[FEATURE 💡]: Enhancement to Active Projects

### ISSUE THREAD

**Issue by warmachine028** [CodeWithAloha/CWAWebsite#33]
## Description
The `Active Projects` section has some scope for improvement
 
- Active project items must have be clickable and they must link to the original project websites
- A Card component for each active project will help us add hover effects to the projects too
- Cursor: pointer can also be added

## Screenshots
![image](https://github.com/CodeWithAloha/CWAWebsite/assets/75939390/eaec83d9-8eb3-43f6-bcb0-6085f87442e7)

I would like to take up this issue under Hacktoberfest-2023 in order to improve the Project

**Comment by LadyDhaga** [comment]
I would like to work on this issue, can you assign it to me?

**Comment by Alexandra-Haynes** [comment]
NavDeep, please go ahead and make a PR with your improvements and we'll discuss them in the PR discussion. I added the hacktoberfest label. I will close this issue now, see you in the PR section. Thanks! 😃

**Comment by warmachine028** [comment]
@Alexandra-Haynes but I wanted to solve this ☹️

**Comment by Alexandra-Haynes** [comment]
Pritam, you are correct, I apologize I didn't see the sentence below the screenshot. Please, make the improvements and submit a PR. Thanks!!!

**Comment by warmachine028** [comment]
Alright I will work on this ASAP.
